name: Deploy web hosting

on:
  push:
    branches:
      - main
    paths:
      - experiments/thebutton/**
      - .github/workflows/thebutton-hosting.yml

jobs:
  build_and_deploy_tb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - run: cd web && npm install
      - run: cd web && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOST_PIXELS_PROD }}
          projectId: lost-pixels-prod
          target: thebutton
          channelId: live
